export const GET_REPOS_REQUEST = 'GET_REPOS_REQUEST'

export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS'

export const GET_REPOS_FAILURE = 'GET_REPOS_FAILURE'

export const SELECT_REPO = 'SELECT_REPO'
